# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = q_test_camera
DESTDIR = ../Win32/Debug
QT += core multimedia network opengl widgets gui multimediawidgets

DEFINES += WIN64 QT_WIDGETS_LIB QT_MULTIMEDIA_LIB QT_MULTIMEDIAWIDGETS_LIB QT_NETWORK_LIB

HEADERS += ./mainwindow.h
SOURCES += ./main.cpp \
    ./mainwindow.cpp
FORMS += ./mainwindow.ui
RESOURCES += q_test_camera.qrc
