######################################################################
# Automatically generated by qmake (2.01a) ? 6 23 02:57:18 2009
######################################################################

TEMPLATE = app
QT += script
TARGET = 
DEPENDPATH += .
INCLUDEPATH += E:/develop/winProjectQt/tutoreal/10/script3/. .

# Input
HEADERS += debugwidget.h mainwindow.h tempwin.h
SOURCES += debugwidget.cpp mainwindow.cpp sample.cpp

contains(QT_CONFIG, scripttools): QT += scripttools
