SET PATH=D:\Program Files\Keil\ARM\BIN40;d:\Program Files\Atmel\AVR Tools\AVR32 Toolchain\bin;D:\Program Files\WinAVR-20100110\bin;D:\Program Files\WinAVR-20100110\utils\bin;d:\Program Files\STMicroelectronics\st_toolset\asm;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files\Altium Designer Summer 09\System;D:\Program Files\Raisonance\Ride\bin;D:\Program Files\Microsoft SQL Server\100\Tools\Binn\;D:\Program Files\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;d:\Program Files\Flash Magic;D:\Program Files\ultraedit\UltraEdit\
SET ARMCC41INC=D:\Program Files\Keil\ARM\RV31\Inc
SET ARMCC41LIB=D:\Program Files\Keil\ARM\RV31\Lib
SET CPU_TYPE=STM32F407IG
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Open407I
SET CPU_CLOCK=0x007A1200
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\main.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\usart.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\lcd.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\asciilib.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\stm32f4xx_it.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmAsm" --Via ".\output\startup_stm32f4xx._ia"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\misc.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\stm32f4xx_fsmc.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\stm32f4xx_gpio.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\stm32f4xx_rcc.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\stm32f4xx_usart.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmCC" --Via ".\output\system_stm32f4xx.__i"
"D:\Program Files\Keil\ARM\BIN40\ArmLink" --Via ".\Output\Project.lnp"
